#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

if [[ -s "/etc/profile.d/vte.sh" ]]; then
    source /etc/profile.d/vte.sh
fi

if [[ -s "$HOME/.commonrc" ]]; then
    source $HOME/.commonrc
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ -x $(which screenfetch) ]]; then
    screenfetch
fi

if [[ -x $(which ponysay) ]]; then
    ponysay -b unicode -q
fi

if [[ -s "$HOME/.commonrc" ]]; then
    source $HOME/.commonrc
fi


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
